"""Native captured-map integration checks against independently generated bytes."""
import argparse
import hashlib
import json
import struct
import subprocess
import sys
import uuid
import zlib
from pathlib import Path

sys.path.insert(0,str(Path(__file__).resolve().parents[1]/'corpus'))
import partition_images as corpus


def field(value,path):
    for part in path.split('.'): value=value[int(part)] if isinstance(value,list) else value[part]
    return value


def main():
    p=argparse.ArgumentParser();p.add_argument('--probe',required=True);p.add_argument('--evidence')
    args=p.parse_args();records=[]
    def run(name,data,blocks=256,unit=512,refusal=None):
        argv=[str(Path(args.probe).resolve()),str(blocks),str(unit)]
        result=subprocess.run(argv,input=data,capture_output=True,timeout=15)
        assert result.returncode==(3 if refusal else 0),(name,result.returncode,result.stdout,result.stderr)
        value=json.loads(result.stdout)
        if refusal: assert value==dict(refusal=refusal),(name,value)
        else:
            assert len(result.stdout)<=48*1024+2,(name,len(result.stdout))
            assert value['capture']==dict(bytes=str(len(data)),declared_bytes=str(blocks*unit),
                sha256=corpus.digest(data),complete=len(data)==blocks*unit,source_consistency='unknown')
            assert value['geometry']==dict(blocks=str(blocks),logical_block_bytes=str(unit))
            assert len(value['copies'])==2 and [x['role'] for x in value['copies']]==['primary','backup']
            assert 'selected' not in value and 'repair' not in value
        records.append(dict(name=name,argv=argv,bytes=len(data),input_sha256=corpus.digest(data),
                            output_sha256=corpus.digest(result.stdout),exit_code=result.returncode))
        return value
    for case in corpus.recipes():
        value=run(case['name'],case['data'])
        for path,expected in case['checks'].items():
            actual=field(value,path);assert actual==expected and type(actual) is type(expected),(case['name'],path,actual,expected)
        for i,row in enumerate(value['mbr']['entries']):
            assert row['raw']==case['data'][446+i*16:462+i*16].hex()
        if case['name']=='gpt-valid':
            for copy in value['copies']:
                assert copy['candidate']['count']==128 and copy['candidate']['active_count']==2
                assert copy['candidate']['omitted']==0
                assert copy['candidate']['entries'][0]['name']=='Alpha'
                assert copy['candidate']['entries'][0]['name_raw']==('Alpha'.encode('utf-16-le')+bytes(62)).hex()
        if 'utf16' in case['name']:
            side=int(case['name'].split('-')[1]);entry=value['copies'][side]['candidate']['entries'][0]
            assert entry['name'] is None and entry['name_status']!=0 and entry['name_raw'].startswith('00d8')
        if case['name']=='gpt-primary-signature':
            assert value['copies'][0]['header']['fields_decoded'] is False
            assert 'disk_guid' not in value['copies'][0]['header']
            assert value['copies'][1]['candidate']['consistent'] is True
    for blocks in [0,1,256]:
        value=run('empty-'+str(blocks),b'',blocks)
        assert value['walks']==[]
        if blocks==0:
            # No LBA zero exists; preserve the C90 DE_BOUNDS refusal, not a table.
            assert value['mbr_status']==7 and value['mbr'] is None
        else:
            assert value['mbr']['issues']==256
            assert all(not entry['decoded'] and entry['raw']=='' for entry in value['mbr']['entries'])
    data=bytes(corpus.gpt())
    for length in [1,445,446,447,461,462,509,510,511,512,513,1023,1024,1030,1152,17407,17408,len(data)-1]:
        value=run('prefix-'+str(length),data[:length])
        assert value['capture']['complete'] is False and value['comparison']==0
        assert value['copies'][1]['header']['issues']==1
        assert value['copies'][1]['header']['fields_decoded'] is False
        for i,row in enumerate(value['mbr']['entries']):assert row['raw']==data[:length][446+i*16:462+i*16].hex()
    for unit in [0,1,511,1024,8192]:run('unsupported-unit-'+str(unit),b'',unit=unit,refusal='image_geometry')
    run('capacity-overflow',b'',blocks=(1<<64)-1,refusal='image_capacity_overflow')
    run('prefix-exceeds-geometry',b'X',blocks=0,refusal='image_geometry')
    run('input-limit',bytes(16*1024*1024+1),blocks=65536,refusal='image_input_limit')
    value=run('exact-input-limit',bytes(16*1024*1024),blocks=32768)
    assert value['capture']['complete'] is True and value['mbr']['issues']==1
    wide=bytearray(256*4096);wide[:512]=data[:512]
    for my,array in [(1,2),(255,223)]:
        wide[my*4096:my*4096+512]=data[my*512:my*512+512]
        wide[array*4096:array*4096+16384]=data[array*512:array*512+16384]
    value=run('4096-byte-blocks',wide,unit=4096)
    assert value['comparison']==1 and value['mbr']['issues']==0
    assert all(x['candidate']['complete'] and x['candidate']['consistent'] for x in value['copies'])
    many=corpus.gpt()
    for side,start in [(0,2*512),(1,223*512)]:
        for i in range(10):
            offset=start+128*i;many[offset:offset+128]=bytes(128)
            many[offset:offset+16]=corpus.TYPE.bytes_le
            many[offset+16:offset+32]=uuid.UUID(int=1 if i==9 else i+1).bytes_le
            struct.pack_into('<QQQ',many,offset+32,34+3*i,35+3*i,0)
            # Control/bidi text stays data; no display normalization here.
            text=('\x1b[31m\u202e'+str(i)).encode('utf-16-le');many[offset+56:offset+56+len(text)]=text
        corpus.array_crc(many,side)
    value=run('omitted-entry-still-validated',many)
    for copy in value['copies']:
        c=copy['candidate'];assert c['active_count']==10 and c['omitted']==2 and len(c['entries'])==8
        assert c['issues'] & 8192 and c['entries'][0]['name'].startswith('\x1b[31m\u202e')
    assert value['comparison']==0
    many=bytearray(256*512);many[:512]=corpus.table([corpus.mbr_entry(15,10,230)])
    for i in range(10):
        lba=10+20*i;entries=[corpus.mbr_entry(7,1,3)]
        if i<9:entries.append(corpus.mbr_entry(15,20*(i+1),230-20*(i+1)))
        many[lba*512:(lba+1)*512]=corpus.table(entries)
    value=run('ebr-detail-limit',many);w=value['walks'][0]
    assert w['count']==10 and w['omitted']==2 and w['complete'] and w['issues']==0
    assert [n['lba'] for n in w['nodes']]==[str(10+20*i) for i in range(8)]
    limited=corpus.gpt()
    struct.pack_into('<Q',limited,512+32,4095);struct.pack_into('<Q',limited,512+40,300)
    struct.pack_into('<Q',limited,512+48,3500);struct.pack_into('<I',limited,512+80,1025)
    corpus.header_crc(limited,512)
    value=run('gpt-entry-budget',limited,blocks=4096)
    assert value['copies'][0]['header']['consistent'] and value['copies'][0]['request_status']==3
    assert 'candidate' not in value['copies'][0]
    malformed=corpus.gpt();struct.pack_into('<I',malformed,512+80,0);corpus.header_crc(malformed,512)
    value=run('invalid-shape-has-no-derived-size',malformed)
    h=value['copies'][0]['header'];assert h['count']==0 and h['issues'] & 256
    assert h['array_bytes'] is None and h['array_blocks'] is None
    assert value['copies'][1]['candidate']['consistent'] and value['comparison']==0
    # Exercise the maximum four bounded walks and both full active arrays. The
    # omitted entries/nodes are still traversed and included in summary findings.
    maximum=bytearray(2048*512);roots=[34,500,970,1440]
    maximum[:512]=corpus.table([corpus.mbr_entry(15,root,400) for root in roots])
    for root in roots:
        for i in range(129):
            lba=root+3*i;rows=[corpus.mbr_entry(7,1,1)]
            if i<128:rows.append(corpus.mbr_entry(15,3*(i+1),400-3*(i+1)))
            maximum[lba*512:(lba+1)*512]=corpus.table(rows)
    rows=bytearray(16384)
    for i in range(128):
        offset=i*128;rows[offset:offset+16]=corpus.TYPE.bytes_le
        rows[offset+16:offset+32]=uuid.UUID(int=i+1).bytes_le
        struct.pack_into('<QQQ',rows,offset+32,34+3*i,35+3*i,0)
        rows[offset+56:offset+128]='\x1b'.encode('utf-16-le')*36
    for my,other,array in [(1,2047,2),(2047,1,2015)]:
        maximum[array*512:array*512+16384]=rows
        struct.pack_into('<8sIIIIQQQQ16sQIII',maximum,my*512,b'EFI PART',0x10000,92,0,0,
            my,other,34,2014,corpus.DISK.bytes_le,array,128,128,zlib.crc32(rows))
        corpus.header_crc(maximum,my*512)
    value=run('maximum-detail-and-walk-budgets',maximum,blocks=2048)
    assert len(value['walks'])==4
    for walk in value['walks']:
        assert walk['count']==128 and walk['omitted']==120 and walk['issues'] & 2048 and not walk['complete']
    for copy in value['copies']:
        c=copy['candidate'];assert c['active_count']==128 and c['omitted']==120 and c['complete']
        assert c['issues'] & 65536  # All original nonterminated names remain findings.
    evidence=dict(passed=True,cases=len(records),probe_sha256=corpus.digest(Path(args.probe).read_bytes()),observations=records)
    if args.evidence:Path(args.evidence).write_text(json.dumps(evidence,indent=2)+'\n',encoding='utf-8',newline='\n')
    print('Image map observations PASS:',len(records))


if __name__=='__main__':main()
