"""Independent cached frontend checks over generated bytes and actual owned readers."""
import argparse,copy,hashlib,importlib.util,json,subprocess,time
from pathlib import Path
from test_storage_queries import disk,volume,packet,descriptor,canonical,digest
from test_volume_namespace import fixture,reply,representation,VOLUME

def selected_registry(root):
    path=root/'tools/build-bootstrap.py';s=importlib.util.spec_from_file_location('disked_observation_static_registry',path);m=importlib.util.module_from_spec(s);s.loader.exec_module(m)
    commands=json.loads((root/'spec/catalog/commands.json').read_bytes())['commands'];syntax=json.loads((root/'spec/catalog/cli-syntax.json').read_bytes())
    schemas={};inputs=json.loads((root/'tools/build-inputs.json').read_bytes())['files']
    for f in (root/'spec/schemas').glob('*.json'):
        v=json.loads(f.read_bytes());schemas[v['$id']]=(v,f)
    return dict(commands=commands,syntax=syntax,schemas=m.parameter_schema_closure(schemas,{x['parameter_schema'] for x in commands if x.get('parameter_schema')},inputs,root))

def synthetic(count,fill,extra=0):
    nodes=[]
    for i in range(count):
        binding=dict(source='synthetic-render',capture_epoch='1',worker_epoch='1',context_digest='sha256:'+'0'*64,frame_digest='sha256:'+'1'*64)
        payload=dict(synthetic=True,ordinal=str(i),parts=['x']*24,text='x'*(fill+(i<extra)))
        label='L'*512;kind='synthetic-observation';id='observation:'+digest(dict(binding=binding,kind=kind,label=label,payload=payload))[7:]
        properties=dict(identity=None,media_generation=None,capacity_bytes=None,label=label,state='unknown',aliases=[],scope='observation-only',physical_identity='unknown',physical_admission=False,mutation_authority=False,freshness='current_observation',observation_binding=binding,observation=payload)
        nodes.append(dict(id=id,kind=kind,properties=properties,observation_refs=[]))
    graph=dict(schema='org.disked.graph/1',capture_id='capture:1',nodes=nodes,edges=[],omissions=[]);graph['revision']=digest(graph);return graph

def main():
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--probe',type=Path,required=True);p.add_argument('--output',type=Path,required=True);p.add_argument('--pointer-bytes',type=int,choices=(4,8),required=True);a=p.parse_args()
    out=a.output.absolute();out.mkdir();probe=a.probe.absolute();root=Path(__file__).resolve().parents[2];registry=selected_registry(root);checks=[];runs=[];children=set()
    def check(label,ok):checks.append(dict(label=label,passed=bool(ok)));assert ok,label
    def run(label,value,expected=0,options=()):
        value=dict(value,registry=registry);data=json.dumps(value,separators=(',',':'),ensure_ascii=True).encode();(out/(label+'.request.json')).write_bytes(data);start=time.monotonic()
        r=subprocess.run([str(probe),*options],input=data,capture_output=True,timeout=45);(out/(label+'.stdout')).write_bytes(r.stdout);(out/(label+'.stderr')).write_bytes(r.stderr)
        runs.append(dict(label=label,command=[str(probe),*options],exit_code=r.returncode,expected_exit=expected,elapsed_seconds=round(time.monotonic()-start,3)))
        check(label+' actual exit',r.returncode==expected and not r.stderr)
        if not r.stdout:return None
        v=json.loads(r.stdout)
        if 'pointer_bytes' in v:check(label+' actual architecture',v['pointer_bytes']==str(a.pointer_bytes))
        observations=[w[k] for w in v.get('workers',[]) for k in ('before','after')]
        observations+=list(v.get('pending_lifecycle',{}).get(k) for k in ('before','during','after') if k in v.get('pending_lifecycle',{}))
        contexts={}
        for w in observations:
            native=w['worker'];identity=(native['pid'],native['created']);children.add(identity)
            check(label+' actual owned identity',int(native['pid'])>0 and int(native['created'])>0)
            check(label+' exact executing code',w['code_sha256']==hashlib.sha256(probe.read_bytes()).hexdigest())
            check(label+' no reader authority',w['claims']==dict(live_namespace=False,physical_admission=False,mutation_authority=False,durable_reconnect=False))
            context={k:w[k] for k in ('attempt_id','observer_epoch','worker_epoch','request_digest','code_sha256')};context.update({k:native[k] for k in ('pid','created')});contexts[digest(context)]=context
        if 'graph' not in v:return v
        g=v['graph'];unbound=copy.deepcopy(g);claimed=unbound.pop('revision');check(label+' independent graph hash',claimed==digest(unbound))
        ids=[n['id'] for n in g['nodes']];observed=[n for n in g['nodes'] if n['properties']['scope']=='observation-only'];fake=[n['id'] for n in g['nodes'] if n['properties']['scope']=='fake-only']
        for n in observed:
            q=n['properties'];binding=q['observation_binding'];payload=q['observation']
            check(label+' no media identity or authority',q['identity'] is None and q['media_generation'] is None and q['capacity_bytes'] is None and q['aliases']==[] and q['physical_identity']=='unknown' and not q['physical_admission'] and not q['mutation_authority'])
            check(label+' independent evidence ID',n['id']=='observation:'+digest(dict(binding=binding,kind=n['kind'],label=q['label'],payload=payload))[7:])
            if contexts:
                check(label+' exact owned context retained',binding['context_digest'] in contexts and payload['worker_context']==contexts[binding['context_digest']])
                check(label+' code identity retained through frontend',payload['worker_context']['code_sha256']==hashlib.sha256(probe.read_bytes()).hexdigest())
        selection=v['inspections']['selected']['result'];check(label+' observation focus never target',selection==dict(target_id=None,observation_id=observed[0]['id'],scope='observation-only',state='present'))
        for name,resp in v['inspections'].items():
            if name=='selected':continue
            result=resp['result'];check(label+' '+name+' exact common inspection',result==v['inspections']['direct']['result'] and result['node']==observed[0] and result['scope']=='cached-observations' and result['node_scope']=='observation-only')
            check(label+' '+name+' no authority in view',not result['physical_admission'] and not result['mutation_authority'] and not result['provider_admitted'])
        listing=v['list']['result'];check(label+' separately typed list IDs',listing['target_ids']==fake and listing['observation_ids']==[n['id'] for n in observed] and listing['graph']==g)
        check(label+' health never calls port',v['health']['status']=='refused' and v['health']['diagnostics'][0]['code']=='observation_not_storage_target' and v['health_calls']=='0')
        assessment=v['capability']['result']['assessment'];check(label+' explanation cannot qualify storage',assessment['target_id'] is None and assessment['observation_id']==observed[0]['id'] and assessment['provider_reference'] is None and not assessment['execution_eligible'] and not assessment['authorizes_execution'])
        check(label+' independent capability dimensions',assessment['checks']==dict(implementation='unavailable',provider='unavailable',qualification='unknown',host_media='unknown',permission='unknown',policy='unavailable',freshness='unknown',target_state='unknown',resources='unavailable',recovery='unavailable'))
        for name in ('gui','tui'):check(label+' '+name+' no target form default',v['forms'][name]['parameters']['target_id']=='')
        check(label+' inspector completion includes evidence',set(v['completions']['inspect']['candidates'])==set(ids))
        # A single matching fake peer may be inserted directly instead of opening
        # the completion chooser. Neither representation may offer evidence.
        health_completion=v['completions']['health'];offered=health_completion['candidates']
        check(label+' health completion excludes evidence',not set(offered)&set(listing['observation_ids']) and not any(n['id'] in health_completion['editor'] for n in observed))
        check(label+' GUI rows retain scope',[(n['id'],n['scope']) for n in v['rows']]==[(n['id'],n['properties']['scope']) for n in g['nodes']])
        rendered=v['rendered'];check(label+' complete GUI JSON display',json.loads(rendered['gui'])['result']==v['topology']['result'])
        body=rendered['tui'][3:-3];check(label+' complete linear TUI JSON display',json.loads('\n'.join(body))['result']==v['topology']['result'])
        records=rendered['shell'];begin=next(i for i,line in enumerate(records) if line.endswith('] result'))+1
        check(label+' complete shell JSON display',json.loads('\n'.join(records[begin:]))['result']==v['topology']['result'])
        for name,data in [('gui',rendered['gui']),('tui','\n'.join(rendered['tui'])),('shell','\n'.join(records))]:
            check(label+' '+name+' inert bounded display',all(c in '\r\n' or 32<=ord(c)<=126 for c in data) and len(data.encode())<=(8388608 if name in ('gui','shell') else 4194304))
        check(label+' shell transcript stays bounded',int(rendered['shell_state']['transcript_bytes'])<=8388608 and rendered['shell_state']['dropped']=='0')
        check(label+' actual frontend memory job',v['frontend_budget_ready'] and v['frontend_memory_bytes']=='268435456')
        retry=v['retry'];before=int(retry['before_capture'].split(':')[1]);after=int(retry['retry_capture'].split(':')[1]);check(label+' allocation failure keeps pointer eligible',retry['allocation_failed'] and after==before+1 and retry['failure_capture']==retry['retry_capture'])
        check(label+' invalid publication rejected atomically',retry['rejected_publication'] in ('duplicate_node','graph_limit'))
        if v['mode']=='owned':
            for name,outcome in retry['stale'].items():check(label+' '+name+' stale action conflict',outcome['status']=='refused' and outcome['diagnostics'][0]['code']=='revision_conflict')
            check(label+' old focus remains missing',retry['selection']==dict(target_id=None,observation_id=observed[0]['id'],scope='observation-only',state='missing'))
            for name,state in retry['refreshed'].items():check(label+' '+name+' refresh never rebinds',state['selection']==retry['selection'])
            check(label+' retained old graph immutable',retry['old_graph']==g)
            current=retry['current_graph'];check(label+' later identical names distinct evidence',set(listing['observation_ids']).isdisjoint(n['id'] for n in current['nodes'] if n['properties']['scope']=='observation-only'))
        if v['mode']=='pending':
            state=v['pending_lifecycle'];check(label+' hung reader survives cached actions',state['before']['status']=='accepted_running' and state['during']['status']=='accepted_running' and state['before']['worker']==state['during']['worker'])
            check(label+' no reader replacement from UI',state['replacement_refused'] and state['after']['worker']['observation']=='exited' and int(state['views_elapsed_ms'])<1500)
        return v
    run('default-profile',dict(mode='default'))
    normal=dict(mode='owned',namespace=fixture(),storage=dict(subjects=[disk(),volume()]));run('owned-parity',normal)
    raw_name='C:\\label\x1b[31m\ud800\u202e\\';d=disk();d['label_units']=['68','27','55296','8238'];b=descriptor(revision=b'\x1b[31m',serial=b'A\x80');d['replies']['descriptor']=[packet(b[:8]),packet(b)]
    v=run('owned-lossless',dict(mode='owned',namespace=fixture(mounts=[[reply((raw_name,))]]),storage=dict(subjects=[d,volume()])))
    check('lossless namespace original representation',any(n['properties'].get('observation',{}).get('name')==representation(raw_name) for n in v['graph']['nodes']))
    check('lossless metadata original representation',any(n['properties'].get('observation',{}).get('resource',{}).get('label',{}).get('original_hex')=='44001b0000d82e20' for n in v['graph']['nodes']))
    run('owned-duplicates',dict(normal,namespace=fixture(names=(VOLUME,VOLUME))))
    d=disk();d['replies']['descriptor']=[packet(ok=False,error=997,returned=9)];run('owned-pending-receipt',dict(normal,storage=dict(subjects=[d,volume()])))
    run('owned-unavailable-port',dict(normal,storage=dict(subjects=[disk()],native_table=True)))
    run('owned-denied-namespace',dict(normal,namespace=fixture(names=(),terminal_error='5')))
    run('reader-hang-cached-views',dict(normal,mode='pending',storage=dict(subjects=[disk()],worker_fault='hang')))
    v=run('synthetic-small',dict(mode='synthetic',count='3',fill='100',extra='0'));check('synthetic graph independently rebuilt',v['graph']==synthetic(3,100))
    base=len(canonical(synthetic(320,0)));remaining=786432-base;fill,extra=divmod(remaining,320);expected=synthetic(320,fill,extra);assert len(canonical(expected))==786432
    v=run('maximum-private-graph',dict(mode='synthetic',count='320',fill=str(fill),extra=str(extra)));check('exact maximum independently constructed graph',v['graph']==expected and len(canonical(v['graph']))==786432)
    check('private display does not extend protocol values',v['wire_result']=='value_limit_exceeded')
    v=run('over-node-limit',dict(mode='synthetic',count='321',fill='0',extra='0'),3);check('node limit typed refusal',v['reason']=='graph_limit')
    fill2,extra2=divmod(remaining+1,320);v=run('over-byte-limit',dict(mode='synthetic',count='320',fill=str(fill2),extra=str(extra2)),3);check('byte limit typed refusal',v['reason']=='message_too_large')
    v=run('distinct-history',dict(mode='history',count='1',fill='0',extra='0'))
    check('more than 1024 observations not media tombstones',v['after_observations']['capture_id']=='capture:1027' and v['selection']['target_id'] is None and v['selection']['state']=='missing')
    check('fake history and identity guards remain enforced',v['limit']=='identity_limit' and v['reuse']=='identity_reuse' and v['media']=='observation_media_claim' and v['frontend_budget_ready'])
    check('original synthetic capture remains bound',v['first']==synthetic(1,0))
    run('unknown-mode',dict(mode='unadmitted'),3);run('unknown-invocation',dict(mode='default'),2,('--observations',))
    result=dict(status='pass',scope='private cached frontend models over actual owned generated readers; no live/product provider admission',pointer_bytes=a.pointer_bytes,controller_executions=len(runs),actual_child_launches=len(children),assertions=len(checks),executions=runs,checks=checks,
        physical_access=False,live_storage_qualified=False,provider_admitted=False,public_protocol_admitted=False,owner_accepted=False,unit_complete=False,remote_writes=False)
    (out/'results.json').write_text(json.dumps(result,indent=2)+'\n',encoding='utf-8',newline='\n');print(json.dumps({k:result[k] for k in ('status','controller_executions','actual_child_launches','assertions')}))
if __name__=='__main__':main()
